accepted = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "GPL-3.0",
    "ISC",
    "LGPL-3.0",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-DFS-2016",
]
ignore-dev-dependencies = true
private.ignore = true
workarounds = [
    "ring",
]
